### PR TITLE
Added notification when plot count changes

### PR DESCRIPTION
**Pull request by jamierf**
I added a LOW level notification that fires when plot count increases.  This happens on startup and whenever plot count increases.

### CODE REVIEW

**Comment by martomi** [comment]
Thanks for the proposal, this will unfortunately cause 30+ daily notifications for people plotting 3+ TB per day so I wouldn't like to merge it to the main branch.

**Comment by Chardmw** [comment]
Can the excess notifications be filtered as part of Issue #77.

**Comment by chadmccune** [comment]
I agree, even though I'm plotting about 10TB a day right now, I'd still
like to have this.

**Comment by jamierf** [comment]
I can see handling it either by adding a config flag just for this event to go to notifications or a flag that enables all low level events to go to the notifications.  Perhaps I'll see if I can figure that out later tonight.

**Comment by andymarden** [comment]
I'm using this mod (I added a pull request where I included time since last plot which is nice) - agree that it could be a config flag just for this message defaulted to false for each notification channel.

**Review by andymarden — APPROVED** [review]
Also include pull request to add time since last plot

**Comment by martomi** [comment]
We've merged and released this feature with this implementation: https://github.com/martomi/chiadog/pull/307

Now it's possible to configure notification for increases / decreases separately.

**Pull request closed without merging**
