### PR TITLE
Add total searches to daily stats

### PR DESCRIPTION
**Pull request by pieterhelsen**
Added overall total number of searches. Also added percentage of total searches for 5s/15 measurements

### CODE REVIEW

**Comment by pieterhelsen** [comment]
changes from running `black` and `flake8` have been reverted as they are already solved in the mqtt-notifier branch

**Comment by martomi** [comment]
I see the mqtt branch is a bit of a mess now 😄 Every individual branch going to dev should be formatted and tested by itself and not depend on any other branch. Once it's merged, the way to go is to rebase other branches on top of dev. Something like this https://gist.github.com/markreid/12e7c2203916b93d23c27a263f6091a0

Do you have an example of how this looks like on phone format? Does it fit the line?

**Comment by pieterhelsen** [comment]
On discord:

Laptop: 
image

Mobile:
Screenshot_20210508-110140_Discord

**Comment by martomi** [comment]
Awesome, thanks for visuals! 

Nitpicking here but I think it would be nice to make it a bit less verbose and compact like this:

```
Search:
  - average: 0.24s over 420 searches
  - over 5s: 20 (4,7%)
  - over 15s: 1 (0.2%) 
```
Do you think it's still readable or better keep the verbose way? In any case we can remove the "average" repetition.

**Comment by pieterhelsen** [comment]
Closed in favor of #95

**Pull request closed without merging**
