### PR TITLE
Improve wallet parser for chia v1.4.0+

### PR DESCRIPTION
**Pull request by djerfy**
Improve wallet parser for Chia 1.4.0+ (tested). Related with issue #340.

### CODE REVIEW

**Comment by martomi** [comment]
Thanks for the fix 🙌 

Please add some examples for the new log format in [this folder](https://github.com/martomi/chiadog/tree/main/tests/chia_log/logs/wallet_added_coin). I suggest to name the files `nominal-before-1.4.0.txt` and `nominal-after-1.4.0.txt` for example.

And a test case reading from the new log format [here](https://github.com/martomi/chiadog/blob/main/tests/chia_log/handlers/test_wallet_added_coin_handler.py).

**Review by martomi — CHANGES_REQUESTED** [review]
Requesting changes as per comment above.

**Comment by djerfy** [comment]
Thanks for your comment. Tests have been added and tested for me (with success and error) 👍

**Comment by martomi** [comment]
Love it, thanks for the quick iteration!

**Review by martomi — APPROVED** [review]

**Pull request merged**
