### PR TITLE
Fix wallet events

### PR DESCRIPTION
**Pull request by skweee**
* amount in debug.log is no longer quoted
* check by sending yourself some mojos using https://faucet.chia.net/

### CODE REVIEW

**Comment by bhy** [comment]
You are right that the amount is no longer quoted thus the parser needs to be fixed. However I think the new regex should accept both the quoted and non-quoted version for the sake of backward compatibility.

**Comment by skweee** [comment]
Thanks for your feedback. Initially I also thought about providing backwards compatibility in this case. However, that would mean supporting older chia versions that still have bugs which compromise the overall health of the network (e.g. negative spends). I therefore think it is better to drop backwards compatibility and point people to upgrading their chia installation.

If there is general concensus about the need for backwards compatibility, I'd be happy to include it in this PR.

**Comment by bhy** [comment]
@skweee that sounds quite reasonable! Thank you for the work!

**Review by martomi — APPROVED** [review]
Thanks for the fix! I agree with you on that one, no need for backward compatibility here.

**Pull request merged**
